# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uteamup < Formula
  desc "UteamUP CLI - Command-line interface for the UteamUP platform"
  homepage "https://uteamup.com"
  version "1.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uteamup/cli/releases/download/1.14.0/uteamup_1.14.0_darwin_amd64.tar.gz"
      sha256 "9ea903fbe31a4badb9d66e8b2fdf7941bb3162bf558243f0202eb6ca2d298b3d"

      define_method(:install) do
        bin.install "uteamup"
        ln_sf bin/"uteamup", bin/"ut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uteamup/cli/releases/download/1.14.0/uteamup_1.14.0_darwin_arm64.tar.gz"
      sha256 "5735375878971881cccdac48cdf4b9fd005b8e786f9d3803eae90ee50eec07be"

      define_method(:install) do
        bin.install "uteamup"
        ln_sf bin/"uteamup", bin/"ut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uteamup/cli/releases/download/1.14.0/uteamup_1.14.0_linux_amd64.tar.gz"
      sha256 "92f69ff4478229a36e2d274bf2b4c888b1c18d10e2594eb2ddb3a22ab834d1d1"
      define_method(:install) do
        bin.install "uteamup"
        ln_sf bin/"uteamup", bin/"ut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uteamup/cli/releases/download/1.14.0/uteamup_1.14.0_linux_arm64.tar.gz"
      sha256 "5c183e639052c048b79bb4f48f09cecfb03136675b358b7e50c9c37da03d5e0c"
      define_method(:install) do
        bin.install "uteamup"
        ln_sf bin/"uteamup", bin/"ut"
      end
    end
  end

  test do
    system "#{bin}/uteamup", "version"
  end
end
